version: '3'
services:
  server1:
    build:
      context: ./server1
    container_name: server1
    ports:
      - "2222:22"
    networks:
      - my_network

  server2:
    build:
      context: ./server2
    container_name: server2
    ports:
      - "2223:22"
    networks:
      - my_network

  server3:
    build:
      context: ./server3
    container_name: server3
    ports:
      - "2224:22"
    networks:
      - my_network

  bastion:
    build:
      context: ./bastion
    container_name: bastion
    ports:
      - "2221:22"
    networks:
      - my_network

networks:
  my_network:
